language: node_js
node_js:
- '4'
- '6'

branches:
  only:
  - master

before_script:
- sudo apt-get install xdg-open
- alias open='xdg-open'
- git config --set user.name 'kamataryo'
- npm install
- npm run lint

script:
- npm test

after_success:
- bash <(curl -s https://codecov.io/bash)
