language: node_js
node_js:
- '4'
- '6'

branches:
  only:
  - master

before_script:
- echo "echo 'Mock command `open` executed.'" > /usr/local/bin/open
- chmod +x /usr/local/bin/open
- git config --set user.name 'kamataryo'
- npm install
- npm run lint

script:
- npm test

after_success:
- bash <(curl -s https://codecov.io/bash)
